#!/usr/bin/env ansible-playbook
---
- hosts: all
  remote_user: root
  gather_facts: no
  tasks:
  - name: Provision guests
    when: provision|default('no')|bool
    block:
    - name: Deploy OpenNebula guests
      import_role: { name: opennebula }
      tags: one

    - name: Deploy base tools
      import_role: { name: base-dnum }
      tags: base

  # FIXME: on Ubuntu, eth1 needs to be configured via DHCP manually
  - name: Mount NFS
    when: nfs_enabled|bool
    import_role: { name: nfs }
    tags: nfs

- hosts: bigbluebutton
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Deploy certificates
    import_role: { name: certificates }
    tags: certs

  - name: Deploy Big Blue Button
    import_role: { name: bigbluebutton }
    tags: bigbluebutton

  - name: Deploy monitoring
    import_role: { name: bigbluebutton, tasks_from: monitoring }
    tags: monitoring

- hosts: scalelite
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Deploy certificates
    import_role: { name: certificates }
    tags: certs

  - name: Install Docker
    import_role: { name: docker }
    tags: docker

  - name: Deploy scalelite load balancer
    import_role: { name: scalelite }
    tags: scalelite

  - name: Deploy monitoring
    import_role: { name: scalelite, tasks_from: monitoring }
    tags: monitoring

- hosts: greenlight
  remote_user: root
  gather_facts: yes
  tasks:
  - name: Deploy certificates
    import_role: { name: certificates }
    tags: certs

  - name: Install Docker
    import_role: { name: docker }
    tags: docker

  - name: Deploy Greenlight
    import_role: { name: greenlight }
    tags: greenlight
